services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      - DOCKER_API_VERSION=1.41
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=admin@ew-production.ru
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - metric

  metrics-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: metrics-backend:latest
    container_name: metrics-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    shm_size: '2gb'
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`metric.pizza.ew-production.ru`) && PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=le
      - traefik.http.routers.backend.priority=20
      - traefik.http.services.backend.loadbalancer.server.port=3000
    networks:
      - metric

  metrics-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://metric.pizza.ew-production.ru/api
    image: metrics-frontend:latest
    container_name: metrics-frontend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`metric.pizza.ew-production.ru`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=le
      - traefik.http.routers.frontend.priority=10
      - traefik.http.services.frontend.loadbalancer.server.port=80
    networks:
      - metric

volumes:
  letsencrypt:

networks:
  metric:
    driver: bridge
